import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import { institutionConfig } from '../config/institutionConfig';

export interface ExportDataPayload {
  title: string;
  subtitle?: string;
  session?: string;
  schoolName?: string;
  udise?: string;
  generatedBy?: string;
  headers: string[];
  rows: (string | number)[][];
  fileName: string;
}

export const exportToCSV = (payload: ExportDataPayload) => {
  const { title, subtitle, schoolName, udise, headers, rows, fileName } = payload;
  
  let csvContent = '\uFEFF'; // BOM for UTF-8 Hindi compatibility
  csvContent += `"${title}"\n`;
  if (subtitle) csvContent += `"${subtitle}"\n`;
  if (schoolName) csvContent += `"विद्यालय: ${schoolName} (UDISE: ${udise || ''})"\n`;
  csvContent += `"संस्था: ${institutionConfig.institutionName} | विकास खंड: ${institutionConfig.block} | जिला: ${institutionConfig.district}"\n`;
  csvContent += `"दिनांक: ${new Date().toLocaleDateString('hi-IN')}"\n\n`;

  csvContent += headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(',') + '\n';

  rows.forEach((row) => {
    csvContent += row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',') + '\n';
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${fileName || 'export'}_${Date.now()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToExcel = (payload: ExportDataPayload) => {
  const { title, schoolName, udise, headers, rows, fileName } = payload;

  const worksheetData: (string | number)[][] = [
    [title],
    [`${institutionConfig.institutionName} (${institutionConfig.block}, ${institutionConfig.district}) - सत्र ${institutionConfig.academicSession}`],
  ];

  if (schoolName) {
    worksheetData.push([`विद्यालय: ${schoolName} (यूडाइस: ${udise || ''})`]);
  }
  worksheetData.push([`रिपोर्ट दिनांक: ${new Date().toLocaleDateString('hi-IN')}`]);
  worksheetData.push([]); // blank row
  worksheetData.push(headers);

  rows.forEach((r) => worksheetData.push(r));

  const ws = XLSX.utils.aoa_to_sheet(worksheetData);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'डेटा रिपोर्ट');

  XLSX.writeFile(wb, `${fileName || 'report'}_${Date.now()}.xlsx`);
};

export const exportMultiSheetExcel = (
  sheetList: { sheetName: string; headers: string[]; rows: (string | number)[][] }[],
  fileName: string
) => {
  const wb = XLSX.utils.book_new();
  sheetList.forEach((sheet) => {
    const data = [sheet.headers, ...sheet.rows];
    const ws = XLSX.utils.aoa_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, sheet.sheetName.slice(0, 31));
  });
  XLSX.writeFile(wb, `${fileName || 'complete_school_dossier'}_${Date.now()}.xlsx`);
};

export const triggerSystemPrint = () => {
  window.print();
};

export const generateQuickPDF = (payload: ExportDataPayload) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const margin = 14;
  let y = 20;

  doc.setFontSize(15);
  doc.text(payload.title || institutionConfig.institutionName, margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.text(payload.subtitle || `${institutionConfig.institutionName} | विकास खंड: ${institutionConfig.block}, जिला: ${institutionConfig.district}`, margin, y);
  y += 6;

  if (payload.schoolName) {
    doc.text(`School: ${payload.schoolName} (UDISE: ${payload.udise || 'N/A'})`, margin, y);
    y += 6;
  }

  doc.setFontSize(9);
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB')} | Generated by: ${payload.generatedBy || 'CAC Portal'} | CAC: ${institutionConfig.cac1.name} (${institutionConfig.cac1.mobile})`, margin, y);
  y += 8;

  doc.line(margin, y, 200 - margin, y);
  y += 6;

  // Simple clean table rendering in PDF
  doc.setFontSize(9);
  doc.text(`Total Records: ${payload.rows.length}`, margin, y);
  y += 8;

  const headerText = payload.headers.slice(0, 6).join('  |  ');
  doc.setFont('helvetica', 'bold');
  doc.text(headerText, margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');

  payload.rows.slice(0, 25).forEach((row) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    const rowText = row.slice(0, 6).map((c) => String(c ?? '')).join('  |  ');
    doc.text(rowText.slice(0, 100), margin, y);
    y += 6;
  });

  if (payload.rows.length > 25) {
    doc.text(`... and ${payload.rows.length - 25} more records (View full dataset in Excel/Print view)`, margin, y + 4);
  }

  doc.save(`${payload.fileName || 'report'}.pdf`);
};
